language: android
jdk: oraclejdk8
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - platform-tools

  licenses:
    - 'android-sdk-license-.+'

before_script:
  - chmod +x gradlew
